### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by frankwang98** [wx9698/carlaviz#72]
carla 0.9.11 ubuntu18, run failed
`python example.py`
```
ActorBlueprint(id=sensor.camera.semantic_segmentation,tags=[semantic_segmentation, camera, sensor])
ActorBlueprint(id=sensor.camera.rgb,tags=[rgb, camera, sensor])
ActorBlueprint(id=sensor.other.rss,tags=[rss, other, sensor])
ActorBlueprint(id=sensor.lidar.ray_cast,tags=[ray_cast, lidar, sensor])
ActorBlueprint(id=sensor.lidar.ray_cast_semantic,tags=[ray_cast_semantic, lidar, sensor])
ActorBlueprint(id=sensor.other.radar,tags=[other, radar, sensor])
ActorBlueprint(id=sensor.other.obstacle,tags=[obstacle, other, sensor])
ActorBlueprint(id=sensor.other.lane_invasion,tags=[lane_invasion, other, sensor])
ActorBlueprint(id=sensor.other.imu,tags=[imu, other, sensor])
ActorBlueprint(id=sensor.other.gnss,tags=[gnss, other, sensor])
ActorBlueprint(id=sensor.camera.depth,tags=[camera, depth, sensor])
ActorBlueprint(id=sensor.other.collision,tags=[collision, other, sensor])
ActorBlueprint(id=sensor.camera.dvs,tags=[dvs, camera, sensor])
Traceback (most recent call last):
  File "example.py", line 127, in <module>
    main()
  File "example.py", line 115, in main
    if lidar is not None:
UnboundLocalError: local variable 'lidar' referenced before assignment
```

**Comment by mjxu96** [comment]
hi unfortuately CarlaViz 0.9.11 is not maintained anymore, could you try with latest carla version?
