### ISSUE TITLE
No map visualization in CarlaViz

### ISSUE THREAD

**Issue by seowwj** [wx9698/carlaviz#9]
I've tried the instructions [here](https://github.com/wx9698/carlaviz#instructions) and [here](https://github.com/wx9698/carlaviz/tree/master/examples) with docker, but the map doesn't seem to visualize on the front end (see image below). Everything else seems to be working (camera visualization, sensor data, etc.)

**Versions**
Carla: 0.9.9.4
CarlaViz: 0.9.9

![image](https://user-images.githubusercontent.com/35338681/95303861-0e169b80-0884-11eb-9b6b-9d2a4f6c7edb.png)

**Comment by wx9698** [comment]
Hi, CarlaViz 0.9.9 only works with Carla 0.9.9.2. You could try other Carla version that CarlaViz supports.

**Comment by seowwj** [comment]
Hi, I've tried with Carla 0.9.9.2, and the same issue still persists.

**Comment by wx9698** [comment]
Hi, I have tried CarlaViz 0.9.9 with Carla 0.9.9.2 and did not reproduce this error... Could you try CarlaViz 0.9.10 and Carla 0.9.10 (not 0.9.10.1) and see it that can resolve the problem?

**Comment by seowwj** [comment]
Hi there,

Here's the docker container output
``` bash
Make sure you have launched the carla server.
Launching backend.
2020-10-08 07:39:58 [INFO]     Connecting to Carla Server on localhost:2000...
2020-10-08 07:39:58 [INFO]     Connected to Carla Server, Server version is: 13fd85b3
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.9 
WARNING: Simulator API version  = 13fd85b3 
2020-10-08 07:40:00 [INFO]     Waiting for a drawing client to connect. Listening to port 8089....
2020-10-08 07:40:00 [INFO]     Waiting for a frontend to connect. Listening to port 8081....
Backend launched.
Launching frontend
yarn run v1.22.4
warning package.json: No license field
$ webpack-dev-server --host 0.0.0.0 --disable-host-check --env.live --progress --hot --open
10% building 1/1 modules 0 active\u2139 \uff62wds\uff63: Project is running at http://0.0.0.0:8082/
\u2139 \uff62wds\uff63: webpack output is served from /
\u2139 \uff62wds\uff63: Content not from webpack is served from /home/carla/carlaviz/frontend
10% building 3/4 modules 1 active ...aviz/frontend/node_modules/babel-loader/lib/index.js??ref--4-0!/home/carla/carlaviz/frontend/node_modules/source-map-loader/index.js!/home/carla/carlaviz/frontend/src/app.jsBrowserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`
93% after chunk asset optimization SourceMapDevToolPluginFrontend launched. Please open your browser
\u2139 \uff62wdm\uff63: Hash: 2843381ccb5ee862e2bf
Version: webpack 4.42.0
Time: 9638ms
Built at: 10/08/2020 7:40:16 AM
                               Asset      Size  Chunks                   Chunk Names
573fe91c6c748074195655e1f0159864.png  7.61 KiB          [emitted]        
                           bundle.js  9.36 MiB     app  [emitted]        app
                       bundle.js.map  11.5 MiB     app  [emitted] [dev]  app
Entrypoint app = bundle.js bundle.js.map
[0] multi (webpack)-dev-server/client?http://0.0.0.0:8082 (webpack)/hot/dev-server.js ./src/app.js 52 bytes {app} [built]
[./node_modules/@deck.gl/core/dist/esm/index.js] 2.78 KiB {app} [built]
[./node_modules/@deck.gl/layers/dist/esm/index.js] 1.01 KiB {app} [built]
[./node_modules/@streetscape.gl/monochrome/dist/esm/index.js] 560 bytes {app} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {app} [built]
[./node_modules/react/index.js] 190 bytes {app} [built]
[./node_modules/streetscape.gl/dist/esm/index.js] 78 bytes {app} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {app} [built]
[./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8082] (webpack)-dev-server/client?http://0.0.0.0:8082 4.29 KiB {app} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {app} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {app} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {app} [built]
[./src/app.js] 10.6 KiB {app} [built]
    + 1454 hidden modules
\u2139 \uff62wdm\uff63: Compiled successfully.
2020-10-08 07:40:21 [INFO]     Drawing client 0 connected
2020-10-08 07:40:21 [INFO]     Update metadata
2020-10-08 07:40:23 [INFO]     Listen sensor: 89, type is: sensor.camera.rgb. Create dummy sensor: 91
2020-10-08 07:40:23 [INFO]     Add camera stream 89 - /camera/rgb/89
2020-10-08 07:40:23 [INFO]     Listen sensor: 90, type is: sensor.lidar.ray_cast. Create dummy sensor: 92
2020-10-08 07:40:23 [INFO]     Update metadata
2020-10-08 07:40:29 [INFO]     Frontend connected
```

And the browser console output
```
[HMR] Waiting for update signal from WDS... log.js:24
deck: deck.gl 8.0.17 - set deck.log.level=1 (or higher) to trace attribute updates init.js:45:4
get map app.js:100:18
[WDS] Hot Module Replacement enabled. client:48
[WDS] Live Reloading enabled. client:52
```

**Comment by wx9698** [comment]
Hi, from the output I do not find any errors. Let me try to build CarlaViz with Carla 0.9.9.4 and will let you know when it is done. You could try 0.9.10 (not 0.9.10.1) before it is finished. Thanks.

**Comment by seowwj** [comment]
Hi, I've tried with CarlaViz 0.9.10, but it's giving me a different error:
```
[INFO] [PAINTER] [2020-10-13 09:44:30,439] : Begin to connect to drawing server at localhost:8089
[INFO] [PAINTER] [2020-10-13 09:44:30,440] : Connected to drawing server at localhost:8089
Traceback (most recent call last):
  File "example.py", line 115, in <module>
    main()
  File "example.py", line 101, in main
    if previous_settings is not None:
UnboundLocalError: local variable 'previous_settings' referenced before assignment
```

Docker output:
```
Make sure you have launched the carla server.
Launching backend.
2020-10-13 07:44:03 [INFO]     Connecting to Carla Server on localhost:2000...
2020-10-13 07:44:03 [INFO]     Connected to Carla Server, Server version is: c8a0b059
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.10 
WARNING: Simulator API version  = c8a0b059 
2020-10-13 07:44:07 [INFO]     Waiting for a drawing client to connect. Listening to port 8089....
2020-10-13 07:44:07 [INFO]     Waiting for a frontend to connect. Listening to port 8081....
2020-10-13 07:44:07 [INFO]     Drawing client 0 connected
2020-10-13 07:44:07 [INFO]     Drawing client 0 connection closed
Backend launched.
Launching frontend
yarn run v1.22.5
warning package.json: No license field
$ webpack-dev-server --host 0.0.0.0 --disable-host-check --env.live --progress --hot --open
10% building 1/1 modules 0 active\u2139 \uff62wds\uff63: Project is running at http://0.0.0.0:8082/
\u2139 \uff62wds\uff63: webpack output is served from /
\u2139 \uff62wds\uff63: Content not from webpack is served from /home/carla/carlaviz/frontend
93% after chunk asset optimization SourceMapDevToolPluginFrontend launched. Please open your browser
\u2139 \uff62wdm\uff63: Hash: 4a617c1fa04fe3dd0eaf
Version: webpack 4.43.0
Time: 10222ms
Built at: 10/13/2020 7:44:22 AM
                               Asset      Size  Chunks                   Chunk Names
573fe91c6c748074195655e1f0159864.png  7.61 KiB          [emitted]        
                           bundle.js  9.66 MiB     app  [emitted]        app
                       bundle.js.map  11.8 MiB     app  [emitted] [dev]  app
Entrypoint app = bundle.js bundle.js.map
[0] multi (webpack)-dev-server/client?http://0.0.0.0:8082 (webpack)/hot/dev-server.js ./src/app.js 52 bytes {app} [built]
[./node_modules/@deck.gl/core/dist/esm/index.js] 3.09 KiB {app} [built]
[./node_modules/@deck.gl/layers/dist/esm/index.js] 1.01 KiB {app} [built]
[./node_modules/@streetscape.gl/monochrome/dist/esm/index.js] 560 bytes {app} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {app} [built]
[./node_modules/react/index.js] 190 bytes {app} [built]
[./node_modules/streetscape.gl/dist/esm/index.js] 78 bytes {app} [built]
[./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8082] (webpack)-dev-server/client?http://0.0.0.0:8082 4.29 KiB {app} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {app} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {app} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {app} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {app} [built]
[./src/app.js] 11.6 KiB {app} [built]
    + 1479 hidden modules
\u2139 \uff62wdm\uff63: Compiled successfully.
2020-10-13 07:44:30 [INFO]     Drawing client 1 connected
2020-10-13 07:44:30 [INFO]     Drawing client 1 connection closed
```

**Comment by wx9698** [comment]
Can you see the map at this time without running the script?

**Comment by seowwj** [comment]
Nope, it still remains blank, but game time and game frames are being updated.

**Comment by wx9698** [comment]
May I ask that are you using you own map or Carla's pre-built map? And could you use chrome as your browser to have a try?

**Comment by seowwj** [comment]
I'm using Carla's pre-built map. Using Chrome solved the issue for me!
Thanks for your help!
